import type { BusinessCategory } from '../types.js';

const INDUSTRY_MAP: Record<string, BusinessCategory> = {
  // home_services
  'plumbing': 'home_services',
  'plumber': 'home_services',
  'hvac': 'home_services',
  'heating': 'home_services',
  'air conditioning': 'home_services',
  'electrical': 'home_services',
  'electrician': 'home_services',
  'roofing': 'home_services',
  'roofer': 'home_services',
  'painting': 'home_services',
  'painter': 'home_services',
  'house painting': 'home_services',
  'landscaping': 'home_services',
  'landscaper': 'home_services',
  'lawn care': 'home_services',
  'lawn service': 'home_services',
  'cleaning': 'home_services',
  'cleaning service': 'home_services',
  'house cleaning': 'home_services',
  'maid service': 'home_services',
  'janitorial': 'home_services',
  'pest control': 'home_services',
  'exterminator': 'home_services',
  'garage door': 'home_services',
  'garage door repair': 'home_services',
  'handyman': 'home_services',
  'home repair': 'home_services',
  'home improvement': 'home_services',
  'tree service': 'home_services',
  'tree removal': 'home_services',
  'arborist': 'home_services',
  'pool': 'home_services',
  'pool service': 'home_services',
  'pool cleaning': 'home_services',
  'junk removal': 'home_services',
  'hauling': 'home_services',
  'fencing': 'home_services',
  'fence': 'home_services',
  'fence company': 'home_services',
  'paving': 'home_services',
  'asphalt': 'home_services',
  'concrete': 'home_services',
  'driveway': 'home_services',
  'siding': 'home_services',
  'gutter': 'home_services',
  'gutters': 'home_services',
  'window cleaning': 'home_services',
  'pressure washing': 'home_services',
  'power washing': 'home_services',
  'carpet cleaning': 'home_services',
  'flooring': 'home_services',
  'remodeling': 'home_services',
  'general contractor': 'home_services',
  'contractor': 'home_services',
  'construction': 'home_services',
  'moving': 'home_services',
  'movers': 'home_services',
  'moving company': 'home_services',
  'locksmith': 'home_services',
  'appliance repair': 'home_services',
  'garage': 'home_services',
  'septic': 'home_services',
  'septic service': 'home_services',
  'waterproofing': 'home_services',
  'foundation repair': 'home_services',
  'insulation': 'home_services',
  'solar': 'home_services',
  'solar installation': 'home_services',

  // health_wellness
  'dental': 'health_wellness',
  'dentist': 'health_wellness',
  'dental office': 'health_wellness',
  'orthodontist': 'health_wellness',
  'chiropractic': 'health_wellness',
  'chiropractor': 'health_wellness',
  'physical therapy': 'health_wellness',
  'physiotherapy': 'health_wellness',
  'med spa': 'health_wellness',
  'medical spa': 'health_wellness',
  'medspa': 'health_wellness',
  'veterinary': 'health_wellness',
  'veterinarian': 'health_wellness',
  'vet': 'health_wellness',
  'animal hospital': 'health_wellness',
  'optometry': 'health_wellness',
  'optometrist': 'health_wellness',
  'eye doctor': 'health_wellness',
  'mental health': 'health_wellness',
  'therapist': 'health_wellness',
  'counseling': 'health_wellness',
  'counselor': 'health_wellness',
  'psychologist': 'health_wellness',
  'psychiatrist': 'health_wellness',
  'dermatology': 'health_wellness',
  'dermatologist': 'health_wellness',
  'urgent care': 'health_wellness',
  'walk-in clinic': 'health_wellness',
  'acupuncture': 'health_wellness',
  'acupuncturist': 'health_wellness',
  'personal trainer': 'health_wellness',
  'personal training': 'health_wellness',
  'fitness trainer': 'health_wellness',
  'yoga': 'health_wellness',
  'yoga studio': 'health_wellness',
  'pilates': 'health_wellness',
  'gym': 'health_wellness',
  'fitness center': 'health_wellness',
  'health club': 'health_wellness',
  'martial arts': 'health_wellness',
  'karate': 'health_wellness',
  'taekwondo': 'health_wellness',
  'boxing': 'health_wellness',
  'dance': 'health_wellness',
  'dance studio': 'health_wellness',
  'spa': 'health_wellness',
  'massage': 'health_wellness',
  'massage therapy': 'health_wellness',
  'day spa': 'health_wellness',
  'nail salon': 'health_wellness',
  'hair salon': 'health_wellness',
  'barber': 'health_wellness',
  'barbershop': 'health_wellness',
  'beauty salon': 'health_wellness',
  'salon': 'health_wellness',
  'aesthetics': 'health_wellness',
  'wellness': 'health_wellness',
  'wellness center': 'health_wellness',
  'pharmacy': 'health_wellness',
  'home health': 'health_wellness',

  // food_beverage
  'restaurant': 'food_beverage',
  'cafe': 'food_beverage',
  'coffee shop': 'food_beverage',
  'coffee': 'food_beverage',
  'bakery': 'food_beverage',
  'food truck': 'food_beverage',
  'catering': 'food_beverage',
  'caterer': 'food_beverage',
  'bar': 'food_beverage',
  'brewery': 'food_beverage',
  'pub': 'food_beverage',
  'winery': 'food_beverage',
  'juice bar': 'food_beverage',
  'smoothie': 'food_beverage',
  'pizza': 'food_beverage',
  'pizzeria': 'food_beverage',
  'ice cream': 'food_beverage',
  'ice cream shop': 'food_beverage',
  'meal prep': 'food_beverage',
  'deli': 'food_beverage',
  'sandwich shop': 'food_beverage',
  'sushi': 'food_beverage',
  'seafood': 'food_beverage',
  'bbq': 'food_beverage',
  'steakhouse': 'food_beverage',
  'fast food': 'food_beverage',
  'donut': 'food_beverage',
  'donut shop': 'food_beverage',
  'bagel': 'food_beverage',
  'taco': 'food_beverage',
  'mexican restaurant': 'food_beverage',
  'chinese restaurant': 'food_beverage',
  'thai restaurant': 'food_beverage',
  'indian restaurant': 'food_beverage',
  'italian restaurant': 'food_beverage',

  // professional
  'law': 'professional',
  'lawyer': 'professional',
  'attorney': 'professional',
  'law firm': 'professional',
  'legal': 'professional',
  'accounting': 'professional',
  'accountant': 'professional',
  'cpa': 'professional',
  'bookkeeper': 'professional',
  'bookkeeping': 'professional',
  'tax preparation': 'professional',
  'tax preparer': 'professional',
  'insurance': 'professional',
  'insurance agent': 'professional',
  'insurance agency': 'professional',
  'real estate': 'professional',
  'realtor': 'professional',
  'real estate agent': 'professional',
  'property management': 'professional',
  'financial advisor': 'professional',
  'financial planner': 'professional',
  'wealth management': 'professional',
  'consulting': 'professional',
  'consultant': 'professional',
  'marketing agency': 'professional',
  'marketing': 'professional',
  'digital marketing': 'professional',
  'advertising': 'professional',
  'seo': 'professional',
  'web design': 'professional',
  'photography': 'professional',
  'photographer': 'professional',
  'videography': 'professional',
  'videographer': 'professional',
  'staffing': 'professional',
  'staffing agency': 'professional',
  'recruiting': 'professional',
  'it': 'professional',
  'it services': 'professional',
  'msp': 'professional',
  'managed services': 'professional',
  'tech support': 'professional',
  'computer repair': 'professional',
  'notary': 'professional',
  'printing': 'professional',
  'print shop': 'professional',
  'architecture': 'professional',
  'architect': 'professional',
  'engineering': 'professional',
  'surveyor': 'professional',
  'interior design': 'professional',
  'interior designer': 'professional',
  'graphic design': 'professional',

  // retail
  'flower shop': 'retail',
  'florist': 'retail',
  'pet store': 'retail',
  'pet shop': 'retail',
  'pet supplies': 'retail',
  'jewelry': 'retail',
  'jewelry store': 'retail',
  'jeweler': 'retail',
  'gift shop': 'retail',
  'gift store': 'retail',
  'bookstore': 'retail',
  'book store': 'retail',
  'thrift': 'retail',
  'thrift store': 'retail',
  'consignment': 'retail',
  'resale': 'retail',
  'vape': 'retail',
  'vape shop': 'retail',
  'cbd': 'retail',
  'smoke shop': 'retail',
  'bike shop': 'retail',
  'bicycle': 'retail',
  'clothing': 'retail',
  'boutique': 'retail',
  'antique': 'retail',
  'antiques': 'retail',
  'furniture store': 'retail',
  'hardware store': 'retail',
  'auto parts': 'retail',
  'liquor store': 'retail',
  'grocery': 'retail',
  'convenience store': 'retail',
  'nursery': 'retail',
  'garden center': 'retail',

  // education
  'daycare': 'education',
  'child care': 'education',
  'childcare': 'education',
  'preschool': 'education',
  'pre-school': 'education',
  'tutoring': 'education',
  'tutor': 'education',
  'music school': 'education',
  'music lessons': 'education',
  'music teacher': 'education',
  'driving school': 'education',
  'private school': 'education',
  'montessori': 'education',
  'learning center': 'education',
  'after school': 'education',
  'test prep': 'education',
  'language school': 'education',
  'art school': 'education',
  'art classes': 'education',
  'swim lessons': 'education',
  'swimming lessons': 'education',
  'coding bootcamp': 'education',
  'trade school': 'education',

  // events
  'wedding venue': 'events',
  'wedding': 'events',
  'event venue': 'events',
  'banquet hall': 'events',
  'dj': 'events',
  'disc jockey': 'events',
  'party rental': 'events',
  'party rentals': 'events',
  'event rental': 'events',
  'event planner': 'events',
  'event planning': 'events',
  'wedding planner': 'events',
  'bowling': 'events',
  'bowling alley': 'events',
  'arcade': 'events',
  'entertainment': 'events',
  'amusement': 'events',
  'escape room': 'events',
  'trampoline park': 'events',
  'go kart': 'events',
  'mini golf': 'events',
  'laser tag': 'events',
  'party bus': 'events',
  'limo': 'events',
  'limousine': 'events',
  'photo booth': 'events',
  'balloon': 'events',
  'balloon artist': 'events',

  // facility
  'laundromat': 'facility',
  'laundry': 'facility',
  'coin laundry': 'facility',
  'car wash': 'facility',
  'auto detailing': 'facility',
  'detailing': 'facility',
  'self-storage': 'facility',
  'self storage': 'facility',
  'storage': 'facility',
  'storage facility': 'facility',
  'coin-op': 'facility',
  'vending': 'facility',
  'parking': 'facility',
  'parking lot': 'facility',
  'parking garage': 'facility',
  'kennel': 'facility',
  'dog boarding': 'facility',
  'pet boarding': 'facility',
  'pet grooming': 'facility',
  'dog grooming': 'facility',
  'auto repair': 'facility',
  'mechanic': 'facility',
  'auto body': 'facility',
  'body shop': 'facility',
  'tire shop': 'facility',
  'oil change': 'facility',
  'transmission': 'facility',
  'towing': 'facility',
  'tow truck': 'facility',
};

const SUBSTRING_FALLBACKS: Array<[string, BusinessCategory]> = [
  ['plumb', 'home_services'],
  ['electric', 'home_services'],
  ['roof', 'home_services'],
  ['paint', 'home_services'],
  ['landscap', 'home_services'],
  ['clean', 'home_services'],
  ['pest', 'home_services'],
  ['handyman', 'home_services'],
  ['tree', 'home_services'],
  ['fenc', 'home_services'],
  ['pav', 'home_services'],
  ['hvac', 'home_services'],
  ['contractor', 'home_services'],
  ['dental', 'health_wellness'],
  ['chiro', 'health_wellness'],
  ['therapy', 'health_wellness'],
  ['spa', 'health_wellness'],
  ['salon', 'health_wellness'],
  ['barber', 'health_wellness'],
  ['fitness', 'health_wellness'],
  ['wellness', 'health_wellness'],
  ['massage', 'health_wellness'],
  ['yoga', 'health_wellness'],
  ['vet', 'health_wellness'],
  ['restaurant', 'food_beverage'],
  ['cafe', 'food_beverage'],
  ['coffee', 'food_beverage'],
  ['bakery', 'food_beverage'],
  ['pizza', 'food_beverage'],
  ['cater', 'food_beverage'],
  ['food', 'food_beverage'],
  ['law', 'professional'],
  ['legal', 'professional'],
  ['account', 'professional'],
  ['insurance', 'professional'],
  ['real estate', 'professional'],
  ['consult', 'professional'],
  ['photo', 'professional'],
  ['market', 'professional'],
  ['florist', 'retail'],
  ['flower', 'retail'],
  ['pet store', 'retail'],
  ['jewel', 'retail'],
  ['boutique', 'retail'],
  ['shop', 'retail'],
  ['daycare', 'education'],
  ['school', 'education'],
  ['tutor', 'education'],
  ['lesson', 'education'],
  ['wedding', 'events'],
  ['event', 'events'],
  ['party', 'events'],
  ['laundro', 'facility'],
  ['laundry', 'facility'],
  ['car wash', 'facility'],
  ['storage', 'facility'],
  ['auto repair', 'facility'],
  ['mechanic', 'facility'],
  ['detail', 'facility'],
  ['grooming', 'facility'],
];

export function getBusinessCategory(industry?: string): BusinessCategory {
  if (!industry) return 'general';

  const lower = industry.toLowerCase().trim();

  // Exact match
  if (lower in INDUSTRY_MAP) return INDUSTRY_MAP[lower];

  // Substring fallback
  for (const [substr, category] of SUBSTRING_FALLBACKS) {
    if (lower.includes(substr)) return category;
  }

  return 'general';
}
